name: Deploy Flutter Web from Development to Main

on:
  push:
    branches: [ development ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout development branch
        uses: actions/checkout@v4
        with:
          ref: development
          fetch-depth: 0

      - name: Setup Flutter 3.32.6
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.6'
          channel: 'stable'

      - name: Run Flutter doctor
        run: flutter doctor

      - name: Clean and get dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Build web project
        run: flutter build web --release --base-href "/portfolio/"

      - name: Deploy to main branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: main
          force_orphan: true