name: Deploy Flutter Web from Development to Main

on:
  push:
    branches: [ development ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout development branch
        uses: actions/checkout@v4
        with:
          ref: development
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.6'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --release

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Deploy to main branch
        run: |
          # Create a temporary directory for deployment
          mkdir -p /tmp/deploy
          cp -r build/web/* /tmp/deploy/
          
          # Switch to main branch (create if doesn't exist)
          git fetch origin main || git checkout --orphan main
          git checkout main || git checkout --orphan main
          
          # Clear the branch and copy new files
          git rm -rf . || true
          cp -r /tmp/deploy/* .
          
          # Add and commit
          git add .
          git commit -m "Deploy Flutter web build from development branch"
          
          # Push to main branch
          git push origin main --force